// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sparse_pair_correlations_cpp
DataFrame sparse_pair_correlations_cpp(NumericMatrix fp, NumericMatrix tf, NumericMatrix fp_rank, NumericMatrix tf_rank, IntegerVector fp_index, IntegerVector tf_index, int n_threads);
RcppExport SEXP _craftgrn_sparse_pair_correlations_cpp(SEXP fpSEXP, SEXP tfSEXP, SEXP fp_rankSEXP, SEXP tf_rankSEXP, SEXP fp_indexSEXP, SEXP tf_indexSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fp(fpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tf(tfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type fp_rank(fp_rankSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tf_rank(tf_rankSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type fp_index(fp_indexSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tf_index(tf_indexSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_pair_correlations_cpp(fp, tf, fp_rank, tf_rank, fp_index, tf_index, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// dense_prediction_stats_cpp
DataFrame dense_prediction_stats_cpp(NumericMatrix fp, NumericMatrix tf, NumericMatrix fp_rank, NumericMatrix tf_rank, CharacterVector fp_id, CharacterVector atac_peak, CharacterVector tf_name, double r_cutoff, double p_cutoff, double fdr_cutoff, int n_threads);
RcppExport SEXP _craftgrn_dense_prediction_stats_cpp(SEXP fpSEXP, SEXP tfSEXP, SEXP fp_rankSEXP, SEXP tf_rankSEXP, SEXP fp_idSEXP, SEXP atac_peakSEXP, SEXP tf_nameSEXP, SEXP r_cutoffSEXP, SEXP p_cutoffSEXP, SEXP fdr_cutoffSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fp(fpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tf(tfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type fp_rank(fp_rankSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tf_rank(tf_rankSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type fp_id(fp_idSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type atac_peak(atac_peakSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type tf_name(tf_nameSEXP);
    Rcpp::traits::input_parameter< double >::type r_cutoff(r_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type p_cutoff(p_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type fdr_cutoff(fdr_cutoffSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(dense_prediction_stats_cpp(fp, tf, fp_rank, tf_rank, fp_id, atac_peak, tf_name, r_cutoff, p_cutoff, fdr_cutoff, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// craftgrn_warplda_fit_cpp
List craftgrn_warplda_fit_cpp(const S4& dtm, int K, int iterations, double alpha, double beta, int seed, double convergence_tol, int n_check_convergence, int n_iter_inference, int n_threads, std::string sampler, Nullable<IntegerVector> ref_topic, Nullable<IntegerVector> ref_proposal, Nullable<IntegerVector> ref_seeds);
RcppExport SEXP _craftgrn_craftgrn_warplda_fit_cpp(SEXP dtmSEXP, SEXP KSEXP, SEXP iterationsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP seedSEXP, SEXP convergence_tolSEXP, SEXP n_check_convergenceSEXP, SEXP n_iter_inferenceSEXP, SEXP n_threadsSEXP, SEXP samplerSEXP, SEXP ref_topicSEXP, SEXP ref_proposalSEXP, SEXP ref_seedsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type dtm(dtmSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type convergence_tol(convergence_tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_check_convergence(n_check_convergenceSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter_inference(n_iter_inferenceSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type sampler(samplerSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type ref_topic(ref_topicSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type ref_proposal(ref_proposalSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type ref_seeds(ref_seedsSEXP);
    rcpp_result_gen = Rcpp::wrap(craftgrn_warplda_fit_cpp(dtm, K, iterations, alpha, beta, seed, convergence_tol, n_check_convergence, n_iter_inference, n_threads, sampler, ref_topic, ref_proposal, ref_seeds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_craftgrn_sparse_pair_correlations_cpp", (DL_FUNC) &_craftgrn_sparse_pair_correlations_cpp, 7},
    {"_craftgrn_dense_prediction_stats_cpp", (DL_FUNC) &_craftgrn_dense_prediction_stats_cpp, 11},
    {"_craftgrn_craftgrn_warplda_fit_cpp", (DL_FUNC) &_craftgrn_craftgrn_warplda_fit_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_craftgrn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
