#' @import data.table
#' @useDynLib craftgrn, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @importFrom graphics mtext symbols
#' @importFrom methods as
#' @importFrom stats aggregate ave end na.omit setNames start
#' @importFrom utils data head modifyList
NULL

utils::globalVariables(c(
  ":", ":=", ".", ".N", ".data",
  "..cond_cols", "..have", "..keep_cols", "..sample_cols",
  "any_bound", "ATAC_bound", "atac_peak", "ATAC_score",
  "bed_end", "bed_start", "bound_peaks", "chr", "comp_id",
  "condition", "condition_support", "corr_fp_tf_p", "corr_fp_tf_p_adj", "corr_fp_tf_r",
  "e_exp", "expressed_genes", "focal_point", "fp_peak", "source_fp_peak",
  "group_size", "i.atac_peak", "i.group_size", "i.new_peak_ID",
  "metric", "mid", "motif_use", "motifs", "N", "new_end", "new_peak_ID",
  "new_start", "peak_ATAC", "peak_chr", "peak_end", "peak_ID",
  "peak_ID_old", "peak_start", "pearson_corr_fp_tf_r", "s_exp",
  "sample_id", "score", "sig_id", "spearman_corr_fp_tf_r",
  "TFBS_chr", "TFBS_end", "TFBS_name", "TFBS_start", "tfbs_id", "tfs", "tfs_clean",
  "type", "value"
))

utils::globalVariables(c(
  "..link_key_cols", "..need", "..tf_gene_doc_cols", "..tf_keep", "..value_cols",
  "abs_log2fc", "assigned", "assigned_topic", "assignment_method", "assignment_status", "bin", "biological_separation_rank", "canonical", "canonical_display",
  "canonical_status", "canonical_symbol", "canonical_tf", "common_candidate_count", "comparison_weight",
  "condition_1", "condition_2", "condition_color", "condition_id", "confidence",
  "confidence_order", "confidence_weight", "context", "context_topic_tf",
  "contributing_genes", "database_label", "document_term_rows",
  "edge_score_for_rank", "effect", "eligible", "expressed", "expression_1",
  "expression_2", "expression_rank", "experimental", "forced_min_terms",
  "fp_max", "fp_score", "fp_sum", "gene_id", "gene_ids",
  "gammafit_candidate", "gene_ambiguous", "gene_assigned_phi", "gene_assigned_topic",
  "gene_canonical", "gene_expr", "gene_gammafit_topic_count", "gene_gammafit_topics",
  "gene_key__", "gene_key_upper", "gene_match", "gene_maxprob_margin", "gene_maxprob_probability",
  "gene_maxprob_topic",
  "gene_match_type", "gene_matched", "gene_present", "gene_topic_pass",
  "gene_topic_score", "global_score", "human_logp", "human_overlap_hits",
  "human_padj", "i.assigned_topics", "i.assignment_method", "i.primary_phi",
  "i.primary_topic", "i.prior_any",
  "i.within_any", "in_any_topic", "is_canonical", "is_formal_match",
  "is_heuristic_match", "item_color", "item_key", "item_label", "item_type",
  "k_for_filter", "log2fc", "log2fc_condition_1_vs_2", "main_title", "match_key",
  "matched", "max_abs_log2fc", "mean_gene_score", "mean_tf_theta",
  "min_maxprob_margin", "min_maxprob_probability",
  "mean_weighted_target_fraction", "method_family", "model_backend",
  "model_label_full", "model_rank", "model_score", "motif_id", "motifs_all",
  "mouse_logp", "mouse_overlap_hits", "mouse_padj", "multivi_preference",
  "log2_expression", "gene_zscore", "n_char", "n_docs", "n_documents",
  "n_expression_genes", "n_expression_universe", "n_pass", "n_regulating_tfs",
  "n_required_tfs_covered", "n_selected_topics", "n_supporting_peaks",
  "n_target_genes", "n_targets_covered", "n_terms", "n_tf_gene_edges",
  "n_tf_peak_gene_triplets", "output_prefix", "over_limit",
  "overall_gene_match_summary", "overall_overlap_gene_keys_list",
  "overall_overlap_gene_symbols", "overall_overlap_gene_symbols_list",
  "overall_overlap_genes", "overall_overlap_genes_list", "overall_overlap_hits",
  "overlap_gene_key_list", "overlap_gene_list", "overlap_gene_symbol_list",
  "overlap_gene_symbols", "overlap_genes", "pair_key", "pass_abs_log2fc",
  "paired_term_id", "pathway_norm_key", "pathway_species", "pathway_term", "payload_chunk", "phi",
  "payload_file", "payload_group", "peak_index", "peak_or_gene", "peak_rank",
  "peak_rank_for_subgrn", "predicted", "present_in_model_terms", "priority_tf",
  "probability", "query", "query_gene_keys", "query_gene_symbols", "query_genes",
  "query_size", "regulator", "required_tf_fraction", "row_id", "row_max_theta",
  "row_type", "scope", "score_plot", "selected", "selected_after_min_terms",
  "selected_database", "selected_pathway_species", "selected_story_topic",
  "selected_tf", "sign_num", "site_index", "stage", "subgrn_context_id",
  "subgrn_group_rank", "SYMBOL", "target", "target_fraction", "target_key",
  "peak_assigned_phi", "peak_assigned_topic", "peak_gammafit_topic_count",
  "peak_gammafit_topics", "peak_maxprob_margin", "peak_maxprob_probability",
  "peak_maxprob_topic", "shared_gammafit_candidate", "shared_gammafit_topics",
  "peak_term_id",
  "target_mass", "term_group", "term_mass", "term_maxprob_margin",
  "term_maxprob_probability", "term_maxprob_selected", "term_maxprob_topic",
  "term_pair_key", "term_score", "term_size",
  "term_source", "term_type", "term_value", "tf_best_score", "tf_expr", "tf_id",
  "tf_present", "tf_primary_topic_num", "tf_rank_for_subgrn", "tf_theta",
  "tf_topic_nums", "tf_topic_score", "tf_topic_scores", "tf_upper",
  "tf_upper_for_rank", "theta_variation", "top20", "topic_assignment",
  "topic_col", "topic_color", "topic_idx__", "topic_rank_score", "topic_score",
  "topic_score_token", "total_selected_topics", "triplet_rank", "UMAP1", "UMAP2",
  "union_active", "value_label", "weighted_target_fraction",
  "within_condition_dispersion"
))

utils::globalVariables(c(
  "..from_cols", "..keep", "..topic_cols", "case_id", "category",
  "cellline", "cluster_label", "cluster_size", "col_index",
  "comparison_id", "comparison_label", "condition_group", "condition_label", "context_type",
  "cond1_id", "cond2_id", "cond1_label", "cond2_label", "cond1_matrix_id",
  "cond2_matrix_id", "ctrl_id", "d2_loglik",
  "active_any", "active_both", "active_cond1", "active_cond2",
  "abs_net_target_gene_count",
  "comparison_group",
  "delta_abs", "delta_fp", "delta_fp_bed_score", "delta_fp_score",
  "delta_link_score",
  "delta_gene", "delta_gene_expr", "de_source", "de_test_id",
  "direction_label", "display_label", "doc_id", "dominant_direction", "down",
  "doc_idx", "doc_weight_total", "dot_top_n_per_topic", "fail",
  "family", "fc_fp_bed_score", "fc_fp_score", "fc_gene_expr", "fc_mag_fp",
  "fc_mag_gene", "fc_mag_tf", "fill_group", "fit_file",
  "fp_bound_case", "fp_bound_cond1", "fp_bound_cond2", "fp_bound_ctrl",
  "fp_dir_sum", "fp_id",
  "fp_score_case", "fp_score_cond1", "fp_score_condition", "fp_score_cond2",
  "fp_score_ctrl",
  "fp_weight", "fp_weight_raw", "gene", "gene_expr_case",
  "gene_expr_cond1", "gene_expr_condition", "gene_expr_cond2",
  "gene_expr_ctrl", "gene_expr_flag_case", "gene_expr_flag_cond1",
  "gene_expr_flag_cond2", "gene_expr_flag_ctrl", "gene_gamma_cutoff", "gene_idx", "gene_name",
  "gene_in", "gene_out", "gene_pass", "gene_prob", "gene_prob_pass", "gene_scale",
  "gene_score", "gene_symbol", "gene_term", "gene_term_id",
  "gene_total", "gene_total_universe", "gene_total_universe_key",
  "gene_weight", "genes", "group_label", "gs_name", "has_matching_peak", "HGNC",
  "in_marker_heatmap", "in_topic", "inner_distance", "inter_distance", "is_sig", "is_topic_top_pathway",
  "item",
  "K", "leading_edge", "link_efdr_p", "link_efdr_q", "link_id",
  "candidate_id", "candidate_source", "distance_to_tss", "fp_center", "point_end", "point_start", "prior_id", "prior_score", "prior_source", "prior_status", "prior_supported", "target_chr", "target_gene", "target_strand", "target_tss", "window_end", "window_start", "within_tss_window",
  "link_pass", "module2_link_pass", "link_score", "link_score_prob", "log2_fc_z_c",
  "log2fc_fp", "log2FC_fp_bed_score", "log2FC_fp_score",
  "log2fc_gene", "log2fc_rna", "log2fc_tf", "log2FC_gene_expr",
  "log2FC_gene_expr_direct", "log2FC_tf_expr", "log2FC_tf_expr_direct", "loglik", "logp",
  "marker_row_order", "max_doc_score", "max_score", "median_log2FC_tf_expr", "method", "method_order",
  "method_setup", "metric_group", "min_topic",
  "model_label", "modality", "n_down_total", "N_gene", "N_peak", "n_target_genes_down",
  "n_target_genes_up", "n_tokens",
  "n_topics", "n_up_total", "net_target_gene_count", "NES", "other_gamma_cutoff",
  "owner_topic", "padj", "padj_rna", "page_label", "panel", "pass", "path",
  "pathway_make_dotplot", "pathway_order", "peak", "peak_id",
  "peak_idx", "peak_key", "peak_pass", "peak_scale", "peak_score",
  "peak_term", "peaks_gamma_cutoff", "perplexity",
  "plot_label", "plot_tf_network_delta", "prob", "pseudo_count", "pseudo_count_bin",
  "p_adj_rna_de_gene", "p_adj_rna_de_tf", "pseudo_count_log", "pval",
  "pvalue_rna", "p_rna_de_gene", "p_rna_de_tf", "rid___", "row_index", "row_order",
  "run_id", "sampler", "score_num", "score_val", "size_val", "sub_cluster_name",
  "target_total", "term_base", "term_id", "term_pass", "term_prefix",
  "term_str", "tf", "tf_doc", "tf_expr_case", "tf_expr_cond1",
  "tf_expr_condition", "tf_expr_cond2", "tf_expr_ctrl", "tf_expr_flag_case",
  "tf_expr_flag_cond1", "tf_expr_flag_cond2", "tf_expr_flag_ctrl", "tf_idx",
  "selected_k", "setup", "setup_label", "shape_value", "split_panel_label",
  "tf_key", "tf_sum_abs_delta", "tf_sum_delta", "tf_term",
  "tf_weight", "tf_weight_norm", "topic", "topic_label", "topic_max",
  "topic_mean_abs_delta", "topic_n_links", "topic_n_target_genes",
  "theta_condition_label_score", "theta_condition_separation_score", "theta_mean",
  "abs_edge_score", "best_distance_to_tss", "best_peak_ID",
  "color", "color_value", "edge_rank", "edge_score", "edge_score_row", "edge_r",
  "from", "max_abs_r_gene", "max_abs_r_rna_gene",
  "label_mode", "mds_label", "median_log2FC_gene_expr", "MDS1", "MDS2",
  "n_edges", "n_genes", "nearest_scaled_dist",
  "n_supporting_links", "n_tfs", "r_gene", "r_rna_gene",
  "scaled_x", "scaled_y", "tf_edge_score_sum", "tf_rank", "tf_target_count", "to",
  "topic_n_TFs", "topic_num", "topic_rank", "total", "value_diff",
  "status_order__", "unit_order__",
  "up", "value_max", "value_min", "value_raw", "value_tol", "w", "weight_raw"
))

utils::globalVariables(c(
  "ambiguous",
  "bar_group", "base_panel_label", "comparison_display",
  "comparison_display_from_edges", "comparison_label_manifest", "count",
  "count_basis", "design_display_label", "doc_design", "doc_display_label",
  "doc_display_label_from_edges", "doc_label", "down_ambiguous",
  "down_primary_theta", "down_primary_topic", "direction_topic_status",
  "fraction", "gammafit_scope_label",
  "k_label", "method_key", "method_label", "method_setup_label", "model_k",
  "model_k_short", "n_items", "n_pass_topics", "margin", "max_theta",
  "membership_pass", "panel_label", "percent", "primary_theta", "primary_topic",
  "primary_topic_num", "row_label", "second_theta", "second_topic", "side",
  "side_x", "src", "status", "tf_display", "theta", "unit", "up_ambiguous",
  "up_primary_theta", "up_primary_topic"
))

utils::globalVariables(c(
  "..heatmap_columns", "colour_value__", "column_label", "doc_index",
  "gene_token_count",
  "expression", "expression_log2", "expression_sum", "gene_inside",
  "expression_max", "expression_min", "expression_tolerance",
  "expression_topic_share", "expression_value",
  "scaled", "centered", "specificity_mass", "specificity_total",
  "expressed_conditions",
  "expression_mass", "mean_topic_share", "topic_share", "topic_share_sum",
  "document_count", "log2fc_vs_reference", "reference_expression",
  "gammafit_topics", "gene_label", "gene_xmax", "i.peak_multiplier",
  "label_inside", "link_index", "link_inside", "links",
  "link_label", "link_xmax", "optimized_aligned", "optimized_assigned_topic",
  "optimized_gene_probability", "optimized_gene_topic",
  "optimized_peak_topic", "optimized_probability__", "optimized_topic__",
  "optimized_posterior_agrees", "optimized_posterior_margin",
  "optimized_posterior_probability", "optimized_posterior_topic",
  "optimized_theta_pass", "optimized_topic", "optimized_topic_num",
  "mean_expression", "n_conditions", "peak_multiplier", "pool_size",
  "pair_index", "peak_independent_topic", "peak_token_count",
  "raw_aligned", "raw_assigned_topic",
  "raw_assignment_status",
  "raw_posterior_agrees", "raw_posterior_margin",
  "raw_posterior_probability", "raw_posterior_topic",
  "raw_target_topic", "raw_theta_pass", "raw_topic", "raw_topic_num",
  "report_key",
  "report_label", "row_order__",
  "recovered_after_merge", "short", "similarity", "target_index",
  "target_key__", "targets", "tf_expression", "tf_expression_median",
  "tf_index", "tf_inside", "tf_label", "tf_xmax", "topic_count",
  "topic_short", "transformed_expression",
  "topic_space", "topic_space_order", "trained_k", "space_order",
  "assigned_topic__", "constrained_topic__", "gene_assignment_status",
  "tf_target_gamma_cutoff"
))
